name: 🚀 Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  deploy-site:
    runs-on: ubuntu-latest

#steps
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 📤 Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./               
          server-dir: /n1foto.com/public_html/
          exclude: |
            **/.git*
            **/.vscode/**
            **/node_modules/**
            **/*.scss
            admin-deploy/**
            db/poligrafy.json
            db/pages/vizitki.json
            img/buklety/uploads/**
            img/listovki/uploads/**

  deploy-admin:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 📤 Deploy admin via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./admin-deploy/
          server-dir: /admin_n1foto_com/public_html/
          exclude: |
            **/.git*
            **/.vscode/**
            **/node_modules/**
            storage/sessions/**

